version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "not on release note"
    reviewers:
      - "aapf/enpro"
    assignees:
      - "aapf/enpro"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "not on release note"
